echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Devops"
echo "Adding new line"
echo "This line is added from github"
echo "This line is added from github and I am learning git"
echo "I am learning branching"
echo "I am learning merging"